Repository ublue-os/image-template, pull requests merged in 2025-05, with the labels that each got.

#103 feat: Add more community examples
  README.md
Labels: documentation, size:XS, lgtm

#107 Fix(justfile): update qemu image name
  Justfile
Labels: bug, size:XS, lgtm

#109 fix(just): fix syntax error
  Justfile
Labels: bug, size:XS
