Repository ublue-os/image-template, pull requests merged in 2025-04, with the labels that each got.

#96 fix: Add rootfs argument to _build-bib
  Justfile
Labels: size:XS, lgtm

#97 fix: fix weird behavior in just run-vm
  Justfile
Labels: bug, size:XS, lgtm

#101 Update README.md
  README.md
Labels: size:XS
