Repository ublue-os/image-template, pull requests merged in 2025-03, with the labels that each got.

#84 ci: make sure renovate uses best-practices preset
  .github/renovate.json5
Labels: dependencies, size:XS, lgtm

#86 ci: use the same renovate config as bluefin-lts
  .github/renovate.json5
  Containerfile
Labels: dependencies, size:S

#88 fix: _rootful_load_image would not copy if the user image was different
  Justfile
Labels: bug, size:XS, lgtm

#82 feat: build in tempdir and move files on success
  .gitignore
  Justfile
Labels: size:S, lgtm

#92 feat: Use bind mounts to keep final image clean
  Containerfile
Labels: enhancement, size:XS

#93 feat: Avoid copying build files into image, add option for linting
  Containerfile
  build_files/build.sh
Labels: enhancement, size:S, lgtm

#95 feat: Enable linting by default
  Containerfile
Labels: size:XS

#91 docs: document the justfile
  README.md
Labels: documentation, size:L, lgtm
